# Generated by Django 3.2.12 on 2023-01-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_genre'),
        ('profiles', '0002_auto_20230113_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='genre',
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ManyToManyField(blank=True, default='', to='misc.Genre'),
        ),
        migrations.RemoveField(
            model_name='artistrequest',
            name='genre',
        ),
        migrations.AddField(
            model_name='artistrequest',
            name='genre',
            field=models.ManyToManyField(blank=True, default='', to='misc.Genre'),
        ),
    ]
