# Generated by Django 3.2.12 on 2023-03-24 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20230324_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbot',
            options={'verbose_name': 'ChatBot status', 'verbose_name_plural': 'ChatBot status'},
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_status', to='profiles.project'),
        ),
    ]
