# Generated by Django 3.2.12 on 2023-01-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20230107_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='languages',
            field=models.TextField(default=''),
        ),
    ]
