# Generated by Django 3.2.12 on 2023-01-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_genre'),
        ('profiles', '0003_auto_20230113_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='skill',
            field=models.ManyToManyField(blank=True, default='', related_name='work_Skill', to='misc.Skill'),
        ),
    ]
