# Generated by Django 3.2.12 on 2023-03-28 06:53

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20230324_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='phone_f',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='status',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=5),
        ),
    ]
