# Generated by Django 3.2.12 on 2023-01-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_genre'),
        ('profiles', '0004_work_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('details', models.TextField(blank=True, default='')),
                ('skills', models.ManyToManyField(blank=True, default='', related_name='templateprojects_Skill', to='misc.Skill')),
            ],
        ),
    ]
