# Generated by Django 3.2.12 on 2023-03-28 06:54

from django.db import migrations
from phonenumber_field.phonenumber import PhoneNumber
from phonenumbers.phonenumberutil import NumberParseException

def link_artists(apps, schema_editor):
    Artist = apps.get_model('profiles', 'Artist')
    for artist in Artist.objects.all():
        try:
            artist.phone_f = PhoneNumber.from_string("+91" + str(artist.phone))
        except NumberParseException as e:
            artist.phone_f = PhoneNumber.from_string("+911234567890")
        artist.save()

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20230328_1223'),
    ]

    operations = [
        migrations.RunPython(link_artists),

        migrations.RemoveField(
        model_name='Artist',
        name='phone',
        ),

        migrations.RenameField(
        model_name='Artist',
        old_name='phone_f',
        new_name='phone',
        ),
    ]
