# Generated by Django 3.2.12 on 2023-04-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_change_phonefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdemo',
            name='document',
            field=models.FileField(default='settings.MEDIA_ROOT\\profile_pics\\default.jpg', max_length=300, upload_to=''),
        ),
    ]
