# Generated by Django 3.2.12 on 2023-01-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20230107_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='languages',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='location',
            field=models.CharField(blank=True, choices=[('Asia', 'Asia'), ('Africa', 'Africa'), ('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America'), ('Australia', 'Australia'), ('Antarctica', 'Antarctica')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='other_arts',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profilePic',
            field=models.ImageField(blank=True, default='', upload_to='artist_pics'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='skill',
            field=models.CharField(blank=True, choices=[('Singer', 'Singer'), ('Dancer', 'Dancer'), ('Actor', 'Actor'), ('Model', 'Model'), ('Musician', 'Musician'), ('Comedian', 'Comedian'), ('Photographer', 'Photographer'), ('Videographer', 'Videographer'), ('Producer', 'Producer'), ('Painter', 'Painter'), ('Writer', 'Writer'), ('Director', 'Director'), ('Other', 'Other')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='manager',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
