# Generated by Django 3.2.12 on 2023-01-18 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20230117_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfee',
            name='project_template',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectfee_to_TemplateProjects_relation', to='profiles.templateprojects'),
        ),
    ]
