# Generated by Django 3.2.12 on 2023-04-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20230425_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdemo',
            name='document',
            field=models.FileField(default='profile_pics\\default.jpg', max_length=255, upload_to='demo'),
        ),
    ]
