# Generated by Django 3.2.12 on 2023-01-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_artist_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='languages',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
