# Generated by Django 3.2.12 on 2023-01-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_artist_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='socialLinks',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
