# Generated by Django 3.2.12 on 2023-01-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_project_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='recommended_artists',
            field=models.ManyToManyField(blank=True, default='', related_name='client_recommended_artists', to='profiles.Artist'),
        ),
    ]
