# Generated by Django 3.2.12 on 2023-04-26 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_projectdemo_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdemo',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectdemo_Project', to='profiles.project'),
        ),
    ]
