# Generated by Django 3.2.12 on 2023-04-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_projectdemo_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='profile_image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='artist',
            name='social_profile',
            field=models.URLField(blank=True, default=''),
        ),
    ]
