# Generated by Django 4.1.7 on 2023-02-20 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('misc', '0004_skill_genres'),
        ('profiles', '0011_client_recommended_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='advance_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='artist_discussion_updates',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='artist_payout_status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Advance Payment Done', 'Advance Payment Done'), ('Full Payment Done', 'Full Payment Done')], default='In Progress', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_artist_payouts',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='final_advance',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='final_fee_settlement_status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='negotiated_advance',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='post_project_client_total_payout',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='production_advance',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='reference_links',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solution_fee',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='templateprojects',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='work_files'),
        ),
        migrations.AddField(
            model_name='templateprojects',
            name='weblink',
            field=models.URLField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='manager',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_to_Manager_relation', to='profiles.manager'),
        ),
        migrations.AlterField(
            model_name='artistfeedback',
            name='artist',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_Artist', to='profiles.artist'),
        ),
        migrations.AlterField(
            model_name='artistrequest',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_Location', to='misc.location'),
        ),
        migrations.AlterField(
            model_name='artistrequest',
            name='rejected_artists',
            field=models.ManyToManyField(default='', related_name='%(class)s_RejectedArtist', to='profiles.artist'),
        ),
        migrations.AlterField(
            model_name='artistrequest',
            name='shortlisted_artists',
            field=models.ManyToManyField(default='', related_name='%(class)s_ShortlistedArtist', to='profiles.artist'),
        ),
        migrations.AlterField(
            model_name='artistrequest',
            name='skill',
            field=models.ManyToManyField(blank=True, default='', related_name='%(class)s_Skill', to='misc.skill'),
        ),
        migrations.AlterField(
            model_name='project',
            name='assigned_artists',
            field=models.ManyToManyField(blank=True, default='', related_name='%(class)s_AssignedArtist', to='profiles.artist'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_Artist', to='profiles.client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_demos',
            field=models.ManyToManyField(blank=True, default='', related_name='%(class)s_ProjectDemo', to='profiles.projectdemo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_fee_Status',
            field=models.CharField(blank=True, choices=[('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid')], default='Unpaid', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_template',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_to_TemplateProjects_relation', to='profiles.templateprojects'),
        ),
        migrations.AlterField(
            model_name='project',
            name='shortlisted_artists',
            field=models.ManyToManyField(blank=True, default='', related_name='%(class)s_shortlistedArtist', to='profiles.artist'),
        ),
        migrations.AlterField(
            model_name='projectdemo',
            name='artist',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_Artist', to='profiles.artist'),
        ),
        migrations.AlterField(
            model_name='projectdemo',
            name='demo_work',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_DemoWork', to='profiles.work'),
        ),
        migrations.AlterField(
            model_name='projectdemo',
            name='project',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_Project', to='profiles.project'),
        ),
        migrations.AlterField(
            model_name='projectfee',
            name='advance_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectfee',
            name='artist_payout_status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Advance Payment Done', 'Advance Payment Done'), ('Full Payment Done', 'Full Payment Done')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='templateprojects',
            name='skills',
            field=models.ManyToManyField(blank=True, default='', related_name='%(class)s_Skill', to='misc.skill'),
        ),
        migrations.AlterField(
            model_name='work',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_Artist', to='profiles.artist'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('Client', 'Client'), ('Artist Manager', 'Artist Manager'), ('Product Manager', 'Product Manager')], default='Client', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
