# Generated by Django 3.2.12 on 2023-01-07 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_artist_sociallinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='owner',
        ),
    ]
