# Generated by Django 3.2.12 on 2023-04-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20230427_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='best_link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='artist',
            name='ctc_per_annum',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='artist',
            name='max_budget',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='artist',
            name='min_budget',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='artist',
            name='relocation',
            field=models.CharField(default=False, max_length=50, null=True),
        ),
    ]
