# Generated by Django 3.2.12 on 2023-01-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_remove_work_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='budgetIdea',
            field=models.TextField(blank=True, default=''),
        ),
    ]
