# Generated by Django 3.2.12 on 2023-04-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20230428_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='weblink',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
