# Generated by Django 3.2.12 on 2023-01-09 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0013_alter_artist_budgetidea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('details', models.TextField(blank=True, default='')),
                ('clientPreviousPayout', models.IntegerField(blank=True, default=0)),
                ('productionSuggestedProjectAdvance', models.FloatField(blank=True, default=0)),
                ('latestProjectAdvance', models.FloatField(blank=True, default=0)),
                ('latestClientPayoutStatus', models.CharField(blank=True, choices=[('In Progres', 'In Progress'), ('Done', 'Done')], default='', max_length=100)),
                ('totalClientPayout', models.FloatField(blank=True, default=0)),
                ('contractDocumentSigningStatus', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, choices=[('Lead', 'Lead'), ('In Progress', 'In Progress'), ('Halt', 'Halt'), ('Finish', 'Finish')], default='', max_length=100)),
                ('brief', models.TextField(blank=True, default='')),
                ('productionSolution', models.TextField(blank=True, default='')),
                ('comments', models.TextField(blank=True, default='')),
                ('postProjectClientFeedback', models.TextField(blank=True, default='')),
                ('projectFeeStatus', models.CharField(blank=True, choices=[('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid')], default='', max_length=100)),
                ('contractStatus', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='work',
            old_name='link',
            new_name='weblink',
        ),
        migrations.AddField(
            model_name='work',
            name='from_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='work',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='manager',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_to_Manager_relation', to='profiles.manager'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='skill',
            field=models.CharField(blank=True, choices=[('Writer', 'Writer'), ('Lyricist', 'Lyricist'), ('Music Producer', 'Music Producer'), ('Vocalist', 'Vocalist'), ('Rapper', 'Rapper'), ('Anchor', 'Anchor'), ('Voice Over Artist', 'Voice Over Artist'), ('Director', 'Director'), ('Video Producer', 'Video Producer'), ('Video Editor', 'Video Editor'), ('Actor', 'Actor'), ('Influencer', 'Influencer'), ('2D Animation Artist', '2D Animation Artist'), ('3D Animation Artist', '3D Animation Artist'), ('Static Graphics Designer', 'Static Graphics Designer'), ('Website Designer', 'Website Designer'), ('Website Developer', 'Website Developer'), ('Augmented Reality Developer', 'Augmented Reality Developer'), ('Virtual Reality Developer', 'Virtual Reality Developer'), ('Game Developer', 'Game Developer')], default='', max_length=100),
        ),
        migrations.CreateModel(
            name='ProjectFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solutionFee', models.FloatField(blank=True, default=0)),
                ('productionAdvance', models.FloatField(blank=True, default=0)),
                ('negotiatedAdvance', models.FloatField(blank=True, default=0)),
                ('finalAdvance', models.FloatField(blank=True, default=0)),
                ('advanceStatus', models.CharField(blank=True, choices=[('In Progress', 'In Progress'), ('Done', 'Done')], default='', max_length=100)),
                ('artistPayoutStatus', models.CharField(choices=[('In Progress', 'In Progress'), ('Done', 'Done')], default='', max_length=100)),
                ('finalFeeSettlementStatus', models.BooleanField(blank=True, default=False)),
                ('postProjectClientTotalPayout', models.FloatField(blank=True, default=0)),
                ('projectFeeStatus', models.BooleanField(blank=True, default=False)),
                ('assignedArtistsPayouts', models.ManyToManyField(default='', to='profiles.Artist')),
                ('clientID', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFee_to_client_relation', to='profiles.client')),
                ('project', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFee_to_Project_relation', to='profiles.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, choices=[('Selected', 'Selected'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected')], default='', max_length=100)),
                ('artist', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectdemo_Artist', to='profiles.artist')),
                ('demoWork', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectdemo_DemoWork', to='profiles.work')),
                ('project', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectdemo_Project', to='profiles.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='assignedArtists',
            field=models.ManyToManyField(blank=True, default='', related_name='project_AssignedArtist', to='profiles.Artist'),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_Artist', to='profiles.client'),
        ),
        migrations.AddField(
            model_name='project',
            name='projectDemo',
            field=models.ManyToManyField(blank=True, default='', related_name='project_ProjectDemo', to='profiles.ProjectDemo'),
        ),
        migrations.AddField(
            model_name='project',
            name='shortlistedArtists',
            field=models.ManyToManyField(blank=True, default='', related_name='project_shortlistedArtist', to='profiles.Artist'),
        ),
        migrations.AddField(
            model_name='project',
            name='showcaseDemos',
            field=models.ManyToManyField(blank=True, default='', to='profiles.Work'),
        ),
        migrations.AddField(
            model_name='client',
            name='projects',
            field=models.ManyToManyField(blank=True, default='', related_name='client_projects', to='profiles.Project'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ArtistRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, choices=[('Writer', 'Writer'), ('Lyricist', 'Lyricist'), ('Music Producer', 'Music Producer'), ('Vocalist', 'Vocalist'), ('Rapper', 'Rapper'), ('Anchor', 'Anchor'), ('Voice Over Artist', 'Voice Over Artist'), ('Director', 'Director'), ('Video Producer', 'Video Producer'), ('Video Editor', 'Video Editor'), ('Actor', 'Actor'), ('Influencer', 'Influencer'), ('2D Animation Artist', '2D Animation Artist'), ('3D Animation Artist', '3D Animation Artist'), ('Static Graphics Designer', 'Static Graphics Designer'), ('Website Designer', 'Website Designer'), ('Website Developer', 'Website Developer'), ('Augmented Reality Developer', 'Augmented Reality Developer'), ('Virtual Reality Developer', 'Virtual Reality Developer'), ('Game Developer', 'Game Developer')], default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('genre', models.CharField(blank=True, default='', max_length=100)),
                ('language', models.CharField(blank=True, default='', max_length=100)),
                ('otherPerformingArts', models.TextField(blank=True, default='')),
                ('budgetRange', models.CharField(blank=True, default='', max_length=100)),
                ('budgetIdea', models.TextField(blank=True, default='')),
                ('productionHiring', models.IntegerField(blank=True, default=0)),
                ('serviceHiring', models.IntegerField(blank=True, default=0)),
                ('target', models.IntegerField(blank=True, default=0)),
                ('comments', models.TextField(blank=True, default='')),
                ('hiringStatus', models.CharField(blank=True, choices=[('In Progress', 'In Progress'), ('Done', 'Done')], default='', max_length=100)),
                ('project', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ArtistRequest_to_Project_relation', to='profiles.project')),
                ('rejectedArtist', models.ManyToManyField(default='', related_name='artistrequest_RejectedArtist', to='profiles.Artist')),
                ('shortlistedArtist', models.ManyToManyField(default='', related_name='artistrequest_ShortlistedArtist', to='profiles.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preProjectFeedback', models.TextField(blank=True, default='')),
                ('onProjectFeedback', models.TextField(blank=True, default='')),
                ('postProjectFeedback', models.TextField(blank=True, default='')),
                ('artist', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artistfeedback_Artist', to='profiles.artist')),
            ],
        ),
    ]
