# Generated by Django 3.2.12 on 2023-04-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_work_weblink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='ctc_per_annum',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='artist',
            name='max_budget',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='artist',
            name='min_budget',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='artist',
            name='relocation',
            field=models.CharField(default=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='social_links',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='work',
            name='weblink',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
