# Generated by Django 3.2.12 on 2023-01-10 07:59

from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20230110_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='agreement',
        ),
        migrations.AddField(
            model_name='artist',
            name='aggreement',
            field=models.FileField(blank=True, default='', upload_to=profiles.models.savenameLocationForAggreement),
        ),
        migrations.AddField(
            model_name='artist',
            name='agreementBool',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='work_files'),
        ),
        migrations.AddField(
            model_name='work',
            name='owner',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='profiles.artist'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='budget_range',
            field=models.CharField(blank=True, choices=[('Less Than 10,000', '<10k'), ('10K - 20k', '10k-20k'), ('20K - 40k', '20k-40k'), ('Above 40K', '>40k')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile_pic',
            field=models.ImageField(blank=True, default='avatar.png', upload_to=profiles.models.saveNameLocationForProfilePic),
        ),
        migrations.AlterField(
            model_name='artist',
            name='skill',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
