# Generated by Django 3.2.12 on 2023-04-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20230428_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='best_link',
            field=models.URLField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile_image',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='artist',
            name='social_profile',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
