# Generated by Django 3.2.12 on 2023-01-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_alter_work_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='owner',
        ),
    ]
