# Generated by Django 3.2.12 on 2023-04-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20230428_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='best_work',
            field=models.BooleanField(default=False),
        ),
    ]
