# Generated by Django 3.2.12 on 2023-04-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_work_best_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='work',
            name='demo_type',
            field=models.CharField(blank=True, choices=[('Instagram', 'Instagram'), ('Youtube', 'Youtube'), ('Soundcloud', 'Soundcloud'), ('Image', 'Image'), ('Video', 'Video'), ('Other Document', 'Other'), ('Other Document', 'Other Document')], default='', max_length=100),
        ),
    ]
