# Generated by Django 3.2.12 on 2023-01-10 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_remove_work_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='owner',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='profiles.artist'),
        ),
    ]
