# Generated by Django 3.2.12 on 2023-01-10 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_work_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='owner',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_Artist', to='profiles.artist'),
        ),
    ]
