# Generated by Django 3.2.12 on 2023-05-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20230428_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='ctc_per_annum',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='artist',
            name='max_budget',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='artist',
            name='min_budget',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='artist',
            name='relocation',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='works_links',
            field=models.ManyToManyField(blank=True, default='', null=True, to='profiles.Work'),
        ),
    ]
