# Generated by Django 3.2.12 on 2023-05-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20230501_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='works_links',
            field=models.ManyToManyField(blank=True, default='', to='profiles.Work'),
        ),
    ]
