# Generated by Django 3.2.12 on 2023-01-10 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_alter_work_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='work_Artist', to='profiles.artist'),
        ),
        migrations.AlterField(
            model_name='work',
            name='weblink',
            field=models.URLField(blank=True, default='', max_length=100),
        ),
    ]
