# Generated by Django 3.2.12 on 2023-01-10 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20230110_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='aggreement',
            new_name='agreement',
        ),
    ]
