# Generated by Django 3.2.12 on 2023-05-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_alter_artist_works_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='best_work',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='work',
            name='from_client',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='work',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='is_demo',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
