# Generated by Django 3.2.12 on 2023-01-10 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_rename_aggreement_artist_agreement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='agreementBool',
            new_name='has_agreement',
        ),
    ]
