# Generated by Django 3.2.12 on 2023-05-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_auto_20230502_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile_image',
            field=models.URLField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='relocation',
            field=models.CharField(blank=True, default='False', max_length=2000, null=True),
        ),
    ]
