# Generated by Django 3.2.12 on 2023-05-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_auto_20230502_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10, null=True),
        ),
    ]
