# Generated by Django 3.2.12 on 2023-05-29 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0024_project_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='production_manager',
            field=models.ForeignKey(blank=True, help_text="Randomly assigned production manager with role 'PM'", limit_choices_to={'role__role': 'PM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_production_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
