# Generated by Django 3.2.12 on 2023-06-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_tag'),
        ('profiles', '0025_project_production_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='tags',
            field=models.ManyToManyField(blank=True, default='', to='misc.Tag'),
        ),
    ]
