# Generated by Django 3.2.12 on 2023-06-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_work_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdemo',
            name='Title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectdemo',
            name='link',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
