# Generated by Django 3.2.12 on 2023-01-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_auto_20230111_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='demo_type',
            field=models.CharField(blank=True, choices=[('Instagram Link', 'Instagram'), ('Youtube Link', 'Youtube'), ('Soundcloud Link', 'Soundcloud'), ('Image', 'Image'), ('Video', 'Video'), ('Other Document', 'Other')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
