# Generated by Django 3.2.12 on 2023-06-11 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_auto_20230611_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdemo',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectdemo_Project', to='profiles.project'),
        ),
    ]
