# Generated by Django 3.2.12 on 2023-01-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_auto_20230112_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
