# Generated by Django 3.2.12 on 2023-01-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_work_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='show_in_top_feed',
            field=models.BooleanField(default=False),
        ),
    ]
