# Generated by Django 3.2.12 on 2023-06-22 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_artist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdemo',
            name='content_product',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectdemo_to_TemplateProjects_relation', to='profiles.templateprojects'),
        ),
    ]
