# Generated by Django 3.2.12 on 2023-01-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_auto_20230113_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='budget_range',
            field=models.CharField(blank=True, choices=[('<10k', 'Less Than 10,000'), ('10k-20k', '10K - 20k'), ('20K - 40k', '20k-40k'), ('>40k', 'Above 40K')], default='Less Than 10,000', max_length=100),
        ),
    ]
