# Generated by Django 3.2.12 on 2023-06-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_alter_project_chat_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='files',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
