# Generated by Django 3.2.12 on 2023-07-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_project_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='email_token',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email_token',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='projectdemo',
            name='status',
            field=models.CharField(blank=True, choices=[('Selected', 'Selected'), ('Shortlisted', 'Shortlisted'), ('Available to sell', 'Available to sell')], default='', max_length=100),
        ),
    ]
