# Generated by Django 3.2.12 on 2023-01-07 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('email', models.EmailField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('skill', models.CharField(choices=[('Singer', 'Singer'), ('Dancer', 'Dancer'), ('Actor', 'Actor'), ('Model', 'Model'), ('Musician', 'Musician'), ('Comedian', 'Comedian'), ('Photographer', 'Photographer'), ('Videographer', 'Videographer'), ('Producer', 'Producer'), ('Painter', 'Painter'), ('Writer', 'Writer'), ('Director', 'Director'), ('Other', 'Other')], default='', max_length=100)),
                ('profilePic', models.ImageField(default='', upload_to='artist_pics')),
                ('location', models.CharField(default='', max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('genre', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('other_arts', models.CharField(default='', max_length=100)),
                ('worksLinks', models.TextField(default='')),
                ('socialLinks', models.TextField(default='')),
                ('phone', models.IntegerField(default=0)),
                ('hasManager', models.BooleanField(default=False)),
                ('budgetRange', models.CharField(default='', max_length=100)),
                ('budgetIdea', models.CharField(default='', max_length=100)),
                ('amNotes', models.TextField(default='')),
                ('pmNotes', models.TextField(default='')),
                ('profesionalRating', models.IntegerField(default=0)),
                ('attitudeRating', models.IntegerField(default=0)),
                ('agreement', models.URLField(default='', max_length=100)),
                ('manager', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profiles.manager')),
            ],
        ),
    ]
