# Generated by Django 3.2.12 on 2023-01-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='password',
        ),
        migrations.AlterField(
            model_name='artist',
            name='location',
            field=models.CharField(choices=[('Asia', 'Asia'), ('Africa', 'Africa'), ('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America'), ('Australia', 'Australia'), ('Antarctica', 'Antarctica')], default='', max_length=100),
        ),
    ]
