# Generated by Django 3.2.12 on 2023-01-07 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_artist_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='worksLinks',
        ),
        migrations.AlterField(
            model_name='artist',
            name='agreement',
            field=models.URLField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='amNotes',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='attitudeRating',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='budgetIdea',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='budgetRange',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='genre',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='hasManager',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='manager',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.manager'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='phone',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='pmNotes',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profesionalRating',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='socialLinks',
            field=models.TextField(default='', null=True),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('link', models.URLField(default='', max_length=100)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profiles.artist')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='worksLink',
            field=models.ManyToManyField(default='', null=True, to='profiles.Work'),
        ),
    ]
