# Generated by Django 3.2.12 on 2023-01-07 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20230107_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='other_arts',
            new_name='otherArts',
        ),
    ]
