# Generated by Django 3.2.12 on 2023-01-07 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_rename_other_arts_artist_otherarts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='manager',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.manager'),
        ),
    ]
