# Generated by Django 3.2.12 on 2023-01-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='genres',
            field=models.ManyToManyField(related_name='skills', to='misc.Genre'),
        ),
    ]
